#  spring.datasource.url = jdbc:mysql://121.4.164.107:3306/xinnanserver?useUnicode=true&characterEncoding=utf-8&serverTimezone=GMT%2B8
  #spring.datasource.username = XinNanServer
  #spring.datasource.password = xj585jx
  ##spring.datasource.driverClassName = com.mysql.jdbc.Driver
  #spring.datasource.driverClassName = com.mysql.cj.jdbc.Driver
  #spring.datasource.hikari.connection-timeout=60000
  #server.port=8080
spring:
  datasource:
    username: xihua
    password: xj585jx
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://121.4.164.107:3306/xihua?useUnicode=true&characterEncoding=utf-8&serverTimezone=GMT%2B8
#    hikari:
#      max-lifetime: 0